### ISSUE TITLE
Is this using rescript or reason?

### ISSUE THREAD

**Issue by bstro** [ryyppy/rescript-nextjs-template#16]
I'm new to rescript/reason/bucklescript but have been reading quite a lot. I am still a bit confused on the differences, but there don't seem to be any files with a `.res` extension in this repo. Is this using Rescript or is it built with the ReasonML syntax? I'm  trying to find a reasonable way to kick off a new project with Rescript.

Thanks!! <3

**Comment by SkinyMonkey** [comment]
I tried to create a .res file and i get a bunch of errors :/

**Comment by ryyppy** [comment]
Hi @bstro 

This template is based on `bs-platform@8.3.0` and allows both, `.res` and `.re` extensions (you can even mix them).

@SkinyMonkey what kind of errors are you talking about?

**Comment by ghost** [comment]
@SkinyMonkey https://github.com/sehyunchung/rescript-nextjs/commit/fba4ba4b9c2252788840678a361cbc2f8071afaf#

When I tried to follow those changes, I ran into one error with _App.res , so I ended up imitating rescript-lang.org's use of _app.js wrapper for now.

> Also, I reverted MainLayout to use reason for now. When I convert it to rescript, it breaks `next build`'s producing of pages that can properly reference the style sheets.

Figured this out, need to add ".res" paths to tailwind.config.js similar to ".re" (cc: @sehyunchung)

**Comment by kanishka-work** [comment]
Possibly, the return type of GetStaticProps should no longer use the "closed" object notation, to be more idiomatic Rescript
