### ISSUE TITLE
Include gitattributes to suppress `js` diff

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#31]
I agree with the choice of including js files in the repo. Consider adding the .gitattributes file that suppresses the diff of the generated files.

**Comment by ghost** [comment]
I would also add the annotiation to mark the js files as binary so that they don't appear in `git commit --verbose`

**Comment by ryyppy** [comment]
oh, we should remove the bsconfig setting of leaving out the generated header... that way, github will detect the generated code and surpress the diff automatically. will fix.

not sure if i want to classify those files as binaries by default. At max, this could be a tip in the readme

**Comment by ghost** [comment]
The most annoying part in my workflow is scrolling past all the js file diffs when crafting my commit message and reminding myself of what was changed.

**Comment by ghost** [comment]
> oh, we should remove the bsconfig setting of leaving out the generated header... that way, github will detect the generated code and surpress the diff automatically. will fix.
> 

Setting documented somewhere?

**Comment by ryyppy** [comment]
@kanishka-work See #32
