### ISSUE TITLE
devdeps

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#36]
Should next-transpile-modules and rescript-react be devDependencies, since they are only used at site build time?

**Comment by ryyppy** [comment]
probably they should, will need to test it!

**Comment by ghost** [comment]
I'm already using this setup. I haven't encountered any issues.

**Comment by ryyppy** [comment]
okay, i am currently having a pending PR #39 that upgrades all dependencies, will change this then.

**Comment by ryyppy** [comment]
Done

**Comment by ghost** [comment]
For now, I put `rescript` in my deps because the std lib is bundled in.

**Comment by ryyppy** [comment]
If you worry about docker image bloat, you can also check out this configuration: https://rescript-lang.org/docs/manual/latest/build-external-stdlib
