### ISSUE TITLE
Use "slug" pages instead of having "pages" directory with wrappers?

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#38]
Instead of creating a wrapper for each rescript page component, you could recommend that for the rare case when people have two pages with the same name, that people can use the following workaround:

* Use a slug style page for each clashing page. For example, use `[index1].res` and `subdir/[index2].res`. In each of those modules, define a `getStaticPaths` with only returns one path: "index".

**Comment by ryyppy** [comment]
This often causes situations where modules export more than they should, ultimately causing Next to disable fast refresh.

If you know what you are doing, you can do it that way, but I'd prefer the default to be the path of least surprises.
