### ISSUE TITLE
Need for FS shim

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#43]
In the rescript-lang site, the fs api appears to only be used by getStaticProps implementations. I never understood why the empty shim is needed if nextjs takes care of compiling and extracting getStaticProps for the node environment. Consider adding more documentation to next.config.js.

**Comment by ryyppy** [comment]
There are some instances where code is getting pulled into e.g. the blog. We recently refactored a lot of code because we switched to a full `mjs` setup, so I am not even sure if this is still relevant anymore. Will need to try.
