### ISSUE TITLE
Keeping cssnano?

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#45]
Do you plan on keeping cssnano after switching to tailwind jit compiler?

**Comment by ryyppy** [comment]
not entirely sure. depends if tailwind jit comes with automatic css minification?

**Comment by ryyppy** [comment]
I'd be keen on removing cssnano. Any idea if NextJS does minification already in a production build?

**Comment by ghost** [comment]
I don't have a definitive answer. There is a handwaving mention of css minification for production in nextjs docs. I also see mentions of cssnano in the guts of nextjs: https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/plugins/css-minimizer-plugin.ts.
