### ISSUE TITLE
Compilation errors?

### ISSUE THREAD

**Issue by FostersData** [ryyppy/rescript-nextjs-template#46]
I'm new to Rescript so not sure whether the problem is the compiler or if this template is doing something strange.

Cloning down the repo fresh, going into `Index.res` and making a small tweak breaks compilation, and I don't know why.
What's wrong with this function? It compiles fine [in the playground](https://rescript-lang.org/try?code=LYewJgrgNgpgBABTgXjgbwFBzgAQE4wCGAxgC4B0xIwADiAHYz2lZyylzCEDW8qAFAD9iACwCWUMAXoBKFAD44AHhpxiUQgGdNAOULAYyAETAARgFoATEcWiJUpsoD0NeRgC+GDOzhgYAM0JoDgE5ZEVMbB9CPDwUOABtAEYAGjhLNIBmAF1zeQApTXIAQVjCAE9Lci4afnoFOHqAajgkmS9sJTAxADc3bE6RJLUNbT0DY1IYAA9Sc0zpqDh-BjnNGGAxUxBJG3QjAHURQg4xTThScXPCbYhSAH4jPIAlIjJyTVI8MXoAc3dnEN+gMlAhgQN0K8SBRPt8-vwAAZwAAqVzgZzghDgmjEtFgFw2NA0U2WIDiWJ0M1IABY4DQ8CAAFYwMhwCA4v5wV4AZWI3xoHAAZCjCBIAO4-MAAYW53PICJknghSicYNYg0sIy0un0hiMU1mVkWpOY5nWm22kk4cwArHs0FD3rCfr9+EYAIoQMTEbhwbmkGKkIyKwGWcHKekwcPYB1vGFfF2I35iDjqBjwESkUg0TQALicTmTlwgpko1CcBE0fLEAvMjFmjM05imeJOMHIRc45XM9KZLNTYC7PYZzNZeGAcHMeH8cA7KYVAILRZEJbLwAr5XKNBo5Sc9dIjfMfkCwTnHGA3d7o5YypcBGBKu6fQ8GCAA).
```rescript
let default = () => {
  let arr = [1, 2, 3]->Js.Array2.map(n => n + 1)

  <div>
    <h1 className="text-3xl font-semibold"> {"What is this about?"->React.string} </h1>
    <P>
      {React.string(` This is a simple template for a Next4 project using ReScript & TailwindCSS.`)}
    </P>
    <h2 className="text-2xl font-semibold mt-5"> {React.string("Quick Start")} </h2>
    <pre>
      {React.string(`git clone https://github.com/rescript-nextjs-template.git my-project cd my-project rm -rf .git`)} //github.com/ryyppy/nextjs-default.git my-project
    </pre>
  </div>
}
```

The compilation error I'm getting is `Fatal error: exception Invalid_argument("String.sub / Bytes.sub")`, but I've also had the same situation throw index out of bounds errors - this is the minimal reproducible example of it.
I found in other cases that the specific ordering of unrelated let bindings within a function sometimes let it compile instead of throwing an error - is that a quirk or expected behaviour?

**Comment by ryyppy** [comment]
Are you on Windows? Did the build work without any previous modification?

**Comment by FostersData** [comment]
The initial build works perfectly, but breaks with this small change.
I've reproduced on Windows, WSL, and in CodeSandbox online (which I think is a Linux environment in Docker).
Do you get the same error? I might have to try loading up a Linux Docker image myself and see if it happens there

**Comment by FostersData** [comment]
Here's the simplest case I can imagine: I forked the repo, [added Docker](https://github.com/FostersData/rescript-nextjs-test/commit/b21b5d5c438da8b7e813ef9c6857c2010ba1495c), and it built fine.

Added `let x = 3` to `Index.res` (see [changes](https://github.com/FostersData/rescript-nextjs-test/commit/a23ed120f72f77a7f22be817a49331aa02e30610)) and it won't compile, with the same errors as above.
Still works on the playground (warning about unused variable as expected but compiles fine).

**Comment by ryyppy** [comment]
Hm, so I just pulled `node:16-buster`, started an interactive shell, cloned my repo (within docker), and made all the proposed changes. I couldn't replicate the same error.

Did you check out the repo on your Windows machine and passed a volume to your docker instance?

Maybe try to set `export OCAMLRUNPARAM=‘b’` before running rescript; that way we will get a more thorough stacktrace.

(I am on Intel / MacOS btw)

**Comment by bobzhang** [comment]
fixed by https://github.com/rescript-lang/syntax/pull/425

**Comment by ryyppy** [comment]
@FostersData Can you try again by upgrading to `rescript@9.1.3`?

**Comment by SamWoolerton** [comment]
That's fantastic thanks! Fixed it immediately.

Sorry for not replying earlier; using Docker fixed it initially but then reocurred as the files got more complex, was trying to get a minimal reproducible example.

Appreciate the help!

**Comment by FostersData** [comment]
That's fantastic thanks! Fixed it immediately.

Sorry for not replying earlier; using Docker fixed it initially but then reocurred as the files got more complex, was trying to get a minimal reproducible example.

Appreciate the help!
