### ISSUE TITLE
Use raw "import" instead of binding to "import"?

### ISSUE THREAD

**Issue by ghost** [ryyppy/rescript-nextjs-template#49]
Given that 

```
  @val external \"import": string => Js.Promise.t<'a> = "import"
```

will produce the following warning once it's actively used in the codebase:

```
Critical dependency: the request of a dependency is an expression
```

Should this template instead recommend that users directly use %raw to invoke `import` inside of Dynamic.dynamic calls?

**Comment by ryyppy** [comment]
What is the generated JS output? Never saw this message before, and I don't understand what this means

**Comment by ghost** [comment]
The body of the import binding becomes:

`return import(prim); `

and I think this triggers Webpack warning that "prim" is a variable instead of a string literal,  through the cryptic "critical dependency" message above.

**Comment by ghost** [comment]
You can reproduce the warning by adding an interface file for the next bindings. The warning may be harmless if the binding gets inlined at the call site and results in a string literal being passed to import. If that is the case, then it would be nice to have a way to annotate the .resi file to tell the compiler to not generate the function when introducing the .resi file.

**Comment by ryyppy** [comment]
Right, it would probably be better to show an example of on an adhoc import usage instead of exposing a `Next.import_` function. Maybe in a page example within the template, and a mention on the README?

**Comment by ghost** [comment]
I am not sure what is best, but however you feel like addressing it works for me.
