### ISSUE TITLE
next.config.js not working for monorepo via yarn workspaces

### ISSUE THREAD

**Issue by danwetherald** [ryyppy/rescript-nextjs-template#51]
Lots of loading issues when looking for node_modules when using yarn workspaces.

https://github.com/ryyppy/rescript-nextjs-template/blob/a5b1a721af68842babc1d4f23550d40c99eaae25/next.config.js#L14-L24

**Comment by ryyppy** [comment]
You can try what @kanishka-work did, and upgrade to `next-transpile-modules@7.1.2` and remove the `pathResDeps` logic and see if it works.

Like here: https://github.com/ryyppy/rescript-nextjs-template/pull/44/files

**Comment by danwetherald** [comment]
> You can try what @kanishka-work did, and upgrade to `next-transpile-modules@7.1.2` and remove the `pathResDeps` logic and see if it works.
> 
> Like here: https://github.com/ryyppy/rescript-nextjs-template/pull/44/files

We were already on 7.2 and just tried commenting out the code, but same issues unfortunately.

**Comment by ryyppy** [comment]
So what are the error messages you are running into? Need more context on what problems webpack stumbles upon... might be enough to tweak the webpack config a little more

**Comment by danwetherald** [comment]
So it turns out its only having an issue with using this binding in a sibling package within the workspace.

https://github.com/bettercart/rescript-dinero

**Comment by ryyppy** [comment]
Did you use pinned-dependencies of some sorts already?

**Comment by danwetherald** [comment]
Yes, for this package within the workspace it has a pinned dep '@bettercart/wonka"

But rescript-dinero is installed traditionally as a dependency within the @bettercart/wonka package.

There is a lot more info here: https://forum.rescript-lang.org/t/yarn-workspaces-example/1826/4

**Comment by ryyppy** [comment]
Let's continue the discussion on the forum post, since this is not specifically related to the NextJS template. Will close this in the meantime.
