### ISSUE TITLE
getStaticProps and getServerSideProps bindings seem to be backwards and missing preview keys from params

### ISSUE THREAD

**Issue by brandonpittman** [ryyppy/rescript-nextjs-template#8]
getStaticProps and getServerSideProps bindings seem to be backwards and missing preview keys from params

**Comment by ryyppy** [comment]
What do you mean by `seem to be backwards`? You mean they are not up to date?

> missing preview keys from params

I never used the preview keys, that's why they are not there yet!

**Comment by ryyppy** [comment]
i added preview keys with #13
